import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/signinone">SigninOne</Link>
        </li>
        <li>
          <Link to="/verification">Verification</Link>
        </li>
        <li>
          <Link to="/finishingpage">Finishingpage</Link>
        </li>
        <li>
          <Link to="/finishingpageone">FinishingpageOne</Link>
        </li>
        <li>
          <Link to="/finishingpagethree">FinishingpageThree</Link>
        </li>
        <li>
          <Link to="/signaturepage">Signaturepage</Link>
        </li>
        <li>
          <Link to="/thankyoupage">Thankyoupage</Link>
        </li>
        <li>
          <Link to="/finishingpagetwo">FinishingpageTwo</Link>
        </li>
        <li>
          <Link to="/signaturedocusignintegrationdisplay">
            SignatureDocusignintegrationdisplay
          </Link>
        </li>
        <li>
          <Link to="/signin">Signin</Link>
        </li>
        <li>
          <Link to="/forgotpassword">Forgotpassword</Link>
        </li>
        <li>
          <Link to="/finishespage">Finishespage</Link>
        </li>
        <li>
          <Link to="/contractspage">Contractspage</Link>
        </li>
        <li>
          <Link to="/contractfullview">Contractfullview</Link>
        </li>
        <li>
          <Link to="/trash">Trash</Link>
        </li>
        <li>
          <Link to="/finishespageone">FinishespageOne</Link>
        </li>
        <li>
          <Link to="/contractspageone">ContractspageOne</Link>
        </li>
        <li>
          <Link to="/contractspagetwo">ContractspageTwo</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
